###服务启动端口号
server:
  port: 8098
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: user-order
  datasource:
    ###会员数据库
    member:
      jdbc-url: jdbc:mysql://localhost:3306/user
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    ###订单数据库
    order:
      jdbc-url: jdbc:mysql://localhost:3306/order
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver

###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka


    ###因为该应用为注册中心，不会注册自己
    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.eurekamember.demo.entity

